image: gradle:8.5-jdk17

default:
  tags:
    - shelllocal

stages:
  - test

integration_test:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew clean test
    - ./gradlew allureReport
  artifacts:
    when: always
    paths:
      - build/reports/
      - build/test-results/
    expire_in: 1 week