image: gradle:alpine


stages:
  - test

Smoke test:
  stage: test
  script:
    - ./gradlew clean test
    - ./gradlew allureReport
  artifacts:
    paths:
      - build/reports/allure-report/allureReport/*
